# Matrizes

In [ ]:
import numpy as np

In [ ]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [ ]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
matriz.shape

(2, 3)

In [ ]:
matriz[0]

array([2, 3, 1])

In [ ]:
matriz[1]

array([4, 5, 7])

In [ ]:
matriz[0][2]

1

In [ ]:
matriz[1][2]

7

In [ ]:
matriz.shape

(2, 3)

In [ ]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  

[2 3 1]
2
3
1
[4 5 7]
4
5
7
